services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    command: ["mongod", "--replSet", "rs0"]

  mongo_setup:
    image: mongo:latest
    container_name: mongo_setup
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
      sleep 10;
      mongo --host mongo:27017 <<EOF
        rs.initiate({
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mongo:27017' }
          ]
        });
        rs.status();
      EOF
      "
