export * from './external.schema';
export * from './observaciones.schema';
export * from './inbox.schema';
export * from './outbox.schema';
export * from './internal.schema';
export * from './external-detail.schema';
export * from './procedure.schema';
export * from './internal-detail.schema';
export * from './communication.schema';
